# 基本的な演算処理

In [2]:
import tensorflow as tf
sess = tf.InteractiveSession()

## 定数(constant op)

In [3]:
# constant op (定数) を定義
a = tf.constant(2)
b = tf.constant(3)

In [4]:
# デフォルトのグラフを立ち上げ、足し算と掛け算を計算
print("a=2, b=3")
print("Addition with constants: {0}".format(sess.run(a+b)))
print("Multiplication with constnats: {0}".format(sess.run(a*b)))

a=2, b=3
Addition with constants: 5
Multiplication with constnats: 6


## 演算(operations)

In [5]:
# add op (追加), mul op (掛け算)を定義
add = tf.add(a, b)
mul = tf.mul(a, b)

In [6]:
print("Addition with variables: {0}".format(sess.run(add)))
print("Multiplication with variables: {0}".format(sess.run(mul)))    

Addition with variables: 5
Multiplication with variables: 6


## 行列演算(matrix multiplication)

In [7]:
# 行列を定義
matrix1 = tf.constant([ [3., 3.] ]) # 1x2 行列
matrix2 = tf.constant([ [2.], [2.] ]) # 2x1　行列

# 行列演算を定義 (matmul: matrix multiplication)
product1 = tf.matmul(matrix1, matrix2) # 1x2, 2x1 => 1x1行列
product2 = tf.matmul(matrix2, matrix1) # 2x1, 1x2 => 2x2行列

In [8]:
print("product1:\n {0}".format(sess.run(product1))) # [ [3 x 2 + 3 x 2] ]
print("product2:\n {0}".format(sess.run(product2))) # [ [3x2, 3x2], [3x2, 3x2] ]

product1:
 [[ 12.]]
product2:
 [[ 6.  6.]
 [ 6.  6.]]


# Reduction

In [9]:
# 合計を求める
x = [[1, 1, 1],
        [1, 1, 1]]
print( tf.reduce_sum(x).eval() ) # すべての合計
print( tf.reduce_sum(x, 0).eval() ) # 0 dimで合計
print( tf.reduce_sum(x, 1).eval() ) # 1 dimで合計
print( tf.reduce_sum(x, 1, keep_dims=True).eval() ) # 次元をを維持

6
[2 2 2]
[3 3]
[[3]
 [3]]


In [10]:
# 平均を求める
x2 = [[1., 1.],
          [2., 2.]]
print( tf.reduce_mean(x2).eval() )
print( tf.reduce_mean(x2, 0).eval() )
print( tf.reduce_mean(x2, 1).eval() )

1.5
[ 1.5  1.5]
[ 1.  2.]
